apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app-name: nginx
    author.name/value: ramchandra
    informatikasmisom.sk/origin: radhika
  annotations:
    data: "{'key': 'value'}"
spec:
  containers:
  - image: nginx
    name: nginx-pod
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    resources: {}