apiVersion: v1
kind: Pod
metadata:
  name: school-pod3
spec:
  containers:
  - image: ritesh/django-school-project:sqlite
    args:
      - "runserver"
      - "0.0.0.0:8002"
    name: school-pod
    ports:
    - containerPort: 8002
    resources: {}
