apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: postgres-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  hostPath:
    path: /home/pocik/Documents/tutorials/kubernetes-basics/033_persistent_volumes_microk8s/db-data


