apiVersion: v1
kind: Pod
metadata:
  name: school-pod2
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - python manage.py migrate; python manage.py runserver 0.0.0.0:8001
    image: ritesh/django-school-project:sqlite
    name: school-pod
    ports:
    - containerPort: 8001
    resources:
      requests:
        memory: "256Mi"
        cpu: "2"
      limits:
        memory: "512Mi"
        cpu: "2"
      
