apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: sleeper
            resources: {}
            command:
              - "sleep"
              - "5"
          restartPolicy: Never
