apiVersion: batch/v1
kind: Job
metadata:
  name: sleeper
spec:
  parallelism: 2
  completions: 4
  template:
    spec:
      containers:
      - image: busybox
        name: sleeper
        resources: {}
        command:
          - "sleep"
          - "5"
      restartPolicy: Never
status: {}
