apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-project  # Sets Deployment name
  namespace: full-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: school-project
  template:
    metadata:
      labels:
        app: school-project
    spec:
      containers:
        - name: school-project
          image: misohu/django-school-project:postgres
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - python manage.py runserver 0.0.0.0:8000
          ports:
            - containerPort: 8000  # Exposes container port
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: postgres
          resources: {}
      initContainers:
      - name: migrate
        image: misohu/django-school-project:postgres
        command:
          - /bin/sh
          - -c
          - python manage.py migrate
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            value: postgres
