apiVersion: v1
kind: Pod
metadata:
  name: school-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - python manage.py runserver 0.0.0.0:8001
    env:
      - name: DATADIR
        value: /db-data/db.sqlite3
    image: misohu/django-school-project:sqlite
    name: school-pod
    ports:
    - containerPort: 8001
    resources: {}
    volumeMounts:
      - name: db-data
        mountPath: /db-data/
  initContainers:
    - name: migrate
      image: misohu/django-school-project:sqlite
      command:
        - /bin/sh
        - -c
        - python manage.py migrate
      volumeMounts:
      - name: db-data
        mountPath: /db-data/
      env:
      - name: DATADIR
        value: /db-data/db.sqlite3
  volumes:
    - name: db-data
      hostPath:
        path: /home/pocik/Documents/tutorials/kubernetes-basics/032_host_path/db-data
        type: DirectoryOrCreate   # optional will create the dir if it does not exist
