apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
  - image: nginx
    name: nginx-pod
    livenessProbe:
      httpGet:
        path: /non-existing-ep
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 3
      failureThreshold: 2
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    resources: {}