apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  restartPolicy: Always
  containers:
  - image: nginx
    name: nginx-pod
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 3
      failureThreshold: 2
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 3
      failureThreshold: 2
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    resources: {}