apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: {}
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: test-secret
        volumeMounts:
          - mountPath: /etc/config
            name: secret-data
      volumes:
        - name: secret-data
          secret:
            secretName: test-secret