apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-rs
  name: nginx-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
