apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-postgres
  namespace: full-deployment
  labels:
    app: postgres-app-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  hostPath:
    path: /home/pocik/Documents/Tutorials/kubernetes-for-beginners/db-data


